### ISSUE TITLE
Publishing Issue

### ISSUE THREAD

**Issue by 91Abdullah** [tarunmangukiya/laravel-image-resizer#1]
Hi,

I added require:  "tarunmangukiya/laravel-image-resizer": "dev-master" into composer.json file and ran composer update after update it is not being able to publish imageresizer.php into config directory. It is returning response nothing to publish. Can you please throw some light on this issue.

Regards,
Abdullah

**Comment by tarunmangukiya** [comment]
Have you added Service Provider in app.php?

Add this lines in your config/app.php,

```
'providers' => [
          TarunMangukiya\ImageResizer\ImageResizerServiceProvider::class,
]

'aliases' => [
          'ImageResizer'      => TarunMangukiya\ImageResizer\Facades\ImageResizer::class,
]
```

Then try to publish the vendor.
Hope it works.

Thanks for your query, I'll update the docs accordingly.
